#!/bin/sh

# PROVIDE: calico
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name='calico'
rcvar='calico_enable'

load_rc_config "${name}"

: ${calico_enable:='NO'}
: ${calico_path:="/var/run/${name}"}
calico_flags="${calico_flags} ${calico_path}"

command='/usr/sbin/daemon'
procname='/usr/local/bin/calico'
pidfile="/var/run/${name}.pid"
required_dirs=$calico_path

child_flags=$calico_flags
child_user=$calico_user
unset calico_flags calico_user
command_args="\
	-p ${pidfile} -T ${name} ${child_user:+-u ${child_user}} \
	-- ${procname} ${child_flags}"

run_rc_command "$1"
