.Dd May 19, 2020
.Dt CALICO 1
.Os
.
.Sh NAME
.Nm calico
.Nd dispatches cat
.
.Sh SYNOPSIS
.Nm
.Op Fl H Ar host
.Op Fl P Ar port
.Op Fl t Ar timeout
.Ar directory
.
.Sh DESCRIPTION
The
.Nm
daemon
dispatches incoming TLS connections
to instances of
.Xr pounce 1
by Server Name Indication (SNI).
Instances of
.Xr pounce 1
should be configured with
.Fl U
to bind to UNIX-domain sockets
in the directory passed to
.Nm .
.
.Pp
Note that
.Nm
is not a proxy.
Incoming connections are passed directly
to instances of
.Xr pounce 1 ,
which handle TLS negotiation.
.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl H Ar host
Bind to
.Ar host .
The default host is localhost.
.It Fl P Ar port
Bind to
.Ar port .
The default port is 6697.
.It Fl t Ar timeout
Set the timeout in milliseconds
after which a connection will be closed
if it has not sent the ClientHello message.
The default timeout is 1000 milliseconds.
.It Ar directory
The path to the directory containing
.Xr pounce 1
UNIX-domain sockets.
.El
.
.Ss Service Configuration
Add the following to
.Pa /etc/rc.conf
to enable the
.Nm
daemon:
.Bd -literal -offset indent
calico_enable="YES"
.Ed
.
.Pp
The default socket directory is
.Pa /var/run/calico .
It can be changed by setting
.Va calico_path .
The
.Xr pounce 1
service can be configured
to listen in this directory
with the following:
.Bd -literal -offset indent
pounce_flags="-U /var/run/calico"
.Ed
.
.Pp
The
.Nm
and
.Xr pounce 1
services can be started and stopped
independently of each other.
.
.Sh EXAMPLES
Obtain certificates for
and dispatch to two instances of
.Xr pounce 1 :
.Bd -literal -offset indent
certbot certonly -d oftc.example.org
certbot certonly -d freenode.example.org
pounce -U /var/run/calico -H oftc.example.org oftc.conf
pounce -U /var/run/calico -H freenode.example.org freenode.conf
calico -H example.org /var/run/calico
.Ed
.Pp
The two instances can be connected to via
.Li oftc.example.org:6697
and
.Li freenode.example.org:6697 ,
respectively.
.
.Sh SEE ALSO
.Xr pounce 1
.
.Sh STANDARDS
.Bl -item
.It
.Rs
.%R RFC 6066
.%A D. Eastlake 3rd
.%Q Huawei
.%T Transport Layer Security (TLS) Extensions: Extension Definitions
.%I IETF
.%D January 2011
.%U https://tools.ietf.org/html/rfc6066
.Re
.
.It
.Rs
.%R RFC 8446
.%A E. Rescorla
.%T The Transport Layer Security (TLS) Protocol Version 1.3
.%I IETF
.%D August 2018
.%U https://tools.ietf.org/html/rfc8446
.Re
.El
.
.Sh AUTHORS
.An June Bug Aq Mt june@causal.agency
.
.Sh BUGS
Send mail to
.Aq Mt list+pounce@causal.agency
or join
.Li #ascii.town
on
.Li chat.freenode.net .
