.Dd May  4, 2021
.Dt POUNCE-NOTIFY 1
.Os
.
.Sh NAME
.Nm pounce-notify
.Nd notifications for pounce
.
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl c Ar cert
.Op Fl k Ar priv
.Op Fl p Ar port
.Op Fl u Ar user
.Op Fl w Ar pass
.Ar host
.Ar command
.
.Sh DESCRIPTION
The
.Nm
program connects to an instance of
.Xr pounce 1
at
.Ar host
and runs
.Ar command
for each private message
or message containing the user's nickname
while the user is marked as away.
The nickname is matched case-sensitively
and must be surrounded by whitespace or punctuation.
Information about the message
is passed to the command
through the environment.
.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl c Ar cert
Load the TLS client certificate from
.Ar cert .
If the private key is in a separate file,
it is loaded with
.Fl k .
.It Fl k Ar priv
Load the TLS client private key from
.Ar priv .
.It Fl p Ar port
Connect to
.Ar port .
The default port is 6697.
.It Fl u Ar user
Set the username to
.Ar user .
The default username is
.Dq pounce-notify .
.It Fl w Ar pass
Log in with the server password
.Ar pass .
.El
.
.Sh ENVIRONMENT
The following variables
are set in the environment of
.Ar command :
.Bl -tag -width "NOTIFY_MESSAGE" -compact
.It Ev NOTIFY_CHANNEL
The name of the channel
in which the message was sent.
Unset if the message was private.
.It Ev NOTIFY_HOST
The hostname of the user who sent the message.
.It Ev NOTIFY_MESSAGE
The content of the message.
.It Ev NOTIFY_NICK
The nickname of the user who sent the message.
.It Ev NOTIFY_TIME
The time the message was sent,
in
.Sy server-time
format.
.It Ev NOTIFY_USER
The username of the user who sent the message.
.It Ev POUNCE_HOST
The host
.Nm
is connected to.
.It Ev POUNCE_PORT
The port
.Nm
is connected to.
.El
.
.Sh SEE ALSO
.Xr pounce 1
.
.Sh AUTHORS
.An June Bug Aq Mt june@causal.agency
.
.Sh BUGS
Send mail to
.Aq Mt list+pounce@causal.agency
or join
.Li #ascii.town
on
.Li chat.freenode.net .
